-- 429: ION-124 — orașele cu angajați în actul rutei devin localități ale liniei (prelungirea prin oraș, §4.1/§5.1) + cifrele §8.7/§8.8 după ION-124.
DO $$
DECLARE n int; t text;
BEGIN
  UPDATE lde_uzine SET reguli_livrare = replace(replace(replace(replace(reguli_livrare, $v0$Nu fac capăt: drumul de acasă al șoferului care doar trece prin sat și orașele din §5.1.$v0$, $n0$Nu fac capăt: drumul de acasă al șoferului care doar trece prin sat și orașele din §5.1, în afară de prelungirea prin oraș (§5.1, ION-124): acolo capătul efectiv al cursei e ultima urcare (tur) sau ultima coborâre (retur) din oraș, cursă cu cursă.$n0$), $v1$și orice loc la ≤ 3 km de porți (Bălți: Dacia, Autogara, Slobozia).$v1$, $n1$și orice loc la ≤ 3 km de porți (Bălți: Dacia, Autogara, Slobozia). PRELUNGIREA PRIN ORAȘ (Ion, 28.09.2026, ION-124: «dacă are oameni din Sîngerei, Copăceni nicicum nu poate fi optimizat»; dezbaterea Claude + Codex, 6 runde, Codex 10/10): un oraș din lista de mai sus în care actul rutei are angajați e localitate a liniei, nu sat exclus; lista rămâne doar pentru orașele fără angajați în actul rutei. Cursa se prelungește prin oraș doar dacă urma arată urcări (tur) sau coborâri (retur) în el: oprire sub 8 km/h cel puțin 15 s la tur și 5 s la retur, durata măsurată până la punctul următor când acesta e la ≤ 50 m și ≤ 5 min (trackerul trimite un singur punct lent pe oprire), locul = mediana punctelor, la ≤ 3 km de oraș și în afara zonei uzinei; cel puțin 3 opriri distincte (≥ 150 m între ele), în fereastra de 45 de minute dinaintea turului sau de după retur și în golul dintre curse; fără staționare peste 5 minute între opriri și capăt; locurile de odihnă (≥ 20 min pe loc, în tot golul) și locul nopții nu contează. Golul dintre un retur și turul următor se împarte la odihna cea mai lungă de ≥ 20 min; fără ea, dacă opririle se suprapun, ambele curse rămân neprelungite și marcate «ambiguu». Cursele vecine nu se suprapun niciodată. Capătul efectiv (ultima oprire din oraș) intră în regulile §8.7 și în ziua ideală §8.8. Săptămâna 14–20.09: 7 curse prelungite (830MUM 5 prin Sîngerei, 186OMM 2 prin Rîșcani), 0 ambigue; celelalte 16 mașini cu oraș pe rută trec doar prin el.$n1$), $v2$regula 1 = 528 km măsurat (628 extrapolat, 4 mașini), 3 = 2.713 (3.225), împreună 3.241 (3.853) km pe săptămână;$v2$, $n2$regula 1 = 528 km măsurat (628 extrapolat, 4 mașini), 3 = 2.691 (3.198), împreună 3.219 (3.826) km pe săptămână (după ION-124);$n2$), $v3$Săptămâna 14–20.09: 5.489 km măsurat (6.525 extrapolat) — acasă între curse 3.882, noaptea (cu weekendul) 1.612, drum mai lung 249, mai scurt decât idealul −254;$v3$, $n3$Săptămâna 14–20.09: 5.424 km măsurat (6.447 extrapolat, după ION-124) — acasă între curse 3.842, noaptea (cu weekendul) 1.612, drum mai lung 223, mai scurt decât idealul −254;$n3$)
   WHERE id = 'DRAXELMAIER_BALTI' AND length(reguli_livrare) = 35037 AND md5(reguli_livrare) = '84362bd7a2c6ac7416d92c1d3b06d4dc';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION '429: textul din bază nu e cel de după 427, rânduri: %', n; END IF;
  SELECT reguli_livrare INTO t FROM lde_uzine WHERE id = 'DRAXELMAIER_BALTI';
  IF length(t) <> 36642 OR md5(t) <> 'e6bc675c26bf3ef117c47287e6c95bde' THEN RAISE EXCEPTION '429: text neașteptat (lungime %, md5 %)', length(t), md5(t); END IF;
END $$;
