-- 438: ION-136 — parcarea propusă (1–2 locuri) în locul zilei ideale ca cifră a raportului (§8.8 → maxim teoretic, §8.9 nou).
DO $$
DECLARE n int; t text;
BEGIN
  UPDATE lde_uzine SET reguli_livrare = replace(replace(reguli_livrare, $v0$8.8 ZIUA IDEALĂ — CIFRA PRINCIPALĂ DE OPTIMIZARE$v0$, $n0$8.8 ZIUA IDEALĂ — MAXIMUL TEORETIC$n0$), $v1$Pe pagină: blocul «Economie față de ziua ideală», deasupra celor 3 reguli.$v1$, $n1$Din 29.09.2026 (ION-136, Ion: «hai maximele teoretice să le scoatem, ele nu pot fi realizate în realitate») ziua ideală nu mai e cifra din raport: e maximul teoretic și baza de calcul pentru 8.9.
8.9 PARCAREA PROPUSĂ — CIFRA PRINCIPALĂ (Ion, 29.09.2026, pe 925FTI: «auto de la Sărata Veche să fie parcată la Fălești, ținând că sunt 2 ture orientativ în aceeași zonă»; «poți oferi 2 locuri propuneri, pe hartă ele să fie evidențiate clar»; dezbaterea Claude + Codex, 6 runde, Codex 10/10). Fiecare mașină primește unul sau două locuri de parcare, aleși dintre toate satele și orașele la ≤ 15 km de capetele curselor ei și casa șoferului; Bălți și parcul Bălți doar dacă mașina deja stă acolo ≥ 60 min (8.7: «rămâne la uzină» nu se propune). Între două curse din locuri diferite (> 1,5 km, fără golurile care în ziua ideală sunt doar muncă) și noaptea, mașina merge la loc și de acolo la plecarea următoare: costul = legătura directă a zilei ideale (8.8; noaptea între ancorele E / S) + ocolul prin loc pe șosea (Valhalla × 1,05) + legăturile interne ale nopții; plimbatul pe loc rămâne muncă. Km de tăiat = km goi făcuți − km goi cu parcarea, pe zilele măsurate, fără nopțile în Bălți și pauze, adus la 5 zile, niciodată negativ și niciodată peste ziua ideală. Al doilea loc doar dacă scade ≥ 20 km pe săptămână și e folosit la ≥ 3 drumuri; la scor apropiat (≤ 20 km/săpt.) câștigă locul unde mașina deja stă ≥ 60 min, apoi un oraș. Fără propunere: mașinile fără zile măsurate, cele în afara totalului și cele unde orice loc ar lungi drumul («rămâne cum e»). Drumul șoferului spre casă nu e socotit. Săptămâna 14–20.09: 4.507 km pe săptămână (4.029 măsurat) față de maximul teoretic 4.777; 15 mașini cu două locuri, 17 peste 100 km (710CWN 534 Lazo, 518MHD 454 Florești, 925FTI 440 Fălești + Ilenuța); fără propunere 024XKY, 293QVT, 386PKP, 549RNK (nicio zi măsurată) și 826GXP (rămâne cum e). Pe pagină: blocul «Parcarea propusă» în locul «Economie față de ziua ideală»; pe harta mașinii locurile P1 / P2 și drumurile propuse.$n1$)
   WHERE id = 'DRAXELMAIER_BALTI' AND length(reguli_livrare) = 37653 AND md5(reguli_livrare) = '9878818ca525b99beb50883bb4b8ac9d';
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION '438: textul din bază nu e cel de după 434 (435–437 nu ating textul), rânduri: %', n; END IF;
  SELECT reguli_livrare INTO t FROM lde_uzine WHERE id = 'DRAXELMAIER_BALTI';
  IF length(t) <> 39591 OR md5(t) <> '0c83211fdbf621392d7da93717c58140' THEN RAISE EXCEPTION '438: text neașteptat (lungime %, md5 %)', length(t), md5(t); END IF;
END $$;
