// Snapshot al tabelei localities (91 de puncte, 04.10.2026) — pentru testele rezolvatorului (ION-224).
// Nu e sursa de adevăr: producția citește tabela vie. Dacă rețeaua se schimbă, se reîmprospătează.
import type { LocalityRow } from './voice-locality';

export const LOCALITIES: LocalityRow[] = [
  { name_ro: "Otaci", name_ru: "Атаки" },
  { name_ro: "Bănești", name_ru: "Банешты" },
  { name_ro: "Bezeda", name_ru: "Безеда" },
  { name_ro: "Bălți", name_ru: "Бельцы" },
  { name_ro: "Beleavinți", name_ru: "Белявинцы" },
  { name_ro: "Berlinți", name_ru: "Берлинць" },
  { name_ro: "Brătușeni", name_ru: "Братушаны" },
  { name_ro: "Briceni", name_ru: "Бричаны" },
  { name_ro: "Brînzeni", name_ru: "Брынзены" },
  { name_ro: "Bîrlădeni", name_ru: "Бырладяны" },
  { name_ro: "Bîrnova", name_ru: "Бырново" },
  { name_ro: "Văratic", name_ru: "Варатик" },
  { name_ro: "Halahora de Sus", name_ru: "Верхние Холохоры" },
  { name_ro: "Viișoara", name_ru: "Виишоара" },
  { name_ro: "Vălcineț", name_ru: "Волчинец" },
  { name_ro: "Hancăuți", name_ru: "Ганкауцы" },
  { name_ro: "Hlina", name_ru: "Глинка" },
  { name_ro: "Hlinaia", name_ru: "Глиное" },
  { name_ro: "Grigorăuca", name_ru: "Григоровка" },
  { name_ro: "Grimăncăuți", name_ru: "Гриманкауцы" },
  { name_ro: "Grimești", name_ru: "Гримешты" },
  { name_ro: "Grinăuți-Raia", name_ru: "Гринауцы-Рая" },
  { name_ro: "Drepcăuți", name_ru: "Дрепкауцы" },
  { name_ro: "Druța", name_ru: "Друца" },
  { name_ro: "Dumeni", name_ru: "Думень" },
  { name_ro: "Dîngeni", name_ru: "Дынжаны" },
  { name_ro: "Edineț", name_ru: "Единец" },
  { name_ro: "Zaicani", name_ru: "Заиканы" },
  { name_ro: "Zăhăreuca", name_ru: "Захареука" },
  { name_ro: "Chișinău", name_ru: "Кишинёв" },
  { name_ro: "Colicăuți", name_ru: "Коликауцы" },
  { name_ro: "Copăceni", name_ru: "Копачены" },
  { name_ro: "Corestăuți", name_ru: "Корестоуцы" },
  { name_ro: "Corjeuți", name_ru: "Коржеуцы" },
  { name_ro: "Corlateni", name_ru: "Корлатены" },
  { name_ro: "Corpaci", name_ru: "Корпачь" },
  { name_ro: "Cotiujeni", name_ru: "Котюжены" },
  { name_ro: "Coteala", name_ru: "Котяла" },
  { name_ro: "Criva", name_ru: "Крива" },
  { name_ro: "Criva Vama", name_ru: "Крива Таможня" },
  { name_ro: "Cupcini", name_ru: "Купчинь" },
  { name_ro: "Larga", name_ru: "Ларга" },
  { name_ro: "Lencăuți", name_ru: "Ленкауцы" },
  { name_ro: "Lipcani", name_ru: "Липканы" },
  { name_ro: "Lopatnic", name_ru: "Лопатник" },
  { name_ro: "Măgdăcești", name_ru: "Магдачешты" },
  { name_ro: "Mereșeuca", name_ru: "Мерешовка" },
  { name_ro: "Mihălășeni", name_ru: "Михалашаны" },
  { name_ro: "Duruitoarea Nouă", name_ru: "Новая Дуруитоаря" },
  { name_ro: "Bădragii Noi", name_ru: "Новые Бадражи" },
  { name_ro: "Bilicenii Noi", name_ru: "Новые Биличены" },
  { name_ro: "Brătușenii Noi", name_ru: "Новые Братушаны" },
  { name_ro: "Gordineștii Noi", name_ru: "Новые Гординешты" },
  { name_ro: "Caracușenii Noi", name_ru: "Новые Каракушаны" },
  { name_ro: "Cuconeștii Noi", name_ru: "Новые Куконешты" },
  { name_ro: "Mihailenii Noi", name_ru: "Новые Михайлены" },
  { name_ro: "Ocnița", name_ru: "Окница" },
  { name_ro: "Ocnița-Sat", name_ru: "Окница-Сат" },
  { name_ro: "Orhei", name_ru: "Орхей" },
  { name_ro: "Paladea", name_ru: "Паладя" },
  { name_ro: "Pașcani", name_ru: "Пашканы" },
  { name_ro: "Pererita", name_ru: "Перерыта" },
  { name_ro: "Intersecția Pelenia", name_ru: "Пересечение Пелиния" },
  { name_ro: "Intersecția Rîșcani", name_ru: "Пересечение Рышканы" },
  { name_ro: "Intersecția Soroca", name_ru: "Пересечение Сороки" },
  { name_ro: "Intersecția Tabani", name_ru: "Пересечение Табаны" },
  { name_ro: "Intersecția Trestieni", name_ru: "Пересечение Трестияны" },
  { name_ro: "Peresecina", name_ru: "Пересечино" },
  { name_ro: "Petrom Rîșcani", name_ru: "Петром Рышканы" },
  { name_ro: "Prepelița", name_ru: "Препелица" },
  { name_ro: "Pîrjota", name_ru: "Пыржота" },
  { name_ro: "Ratuș", name_ru: "Ратуш" },
  { name_ro: "Recea", name_ru: "Реча" },
  { name_ro: "Ruseni", name_ru: "Русяны" },
  { name_ro: "Rîșcani", name_ru: "Рышканы" },
  { name_ro: "Slobotca", name_ru: "Слободка" },
  { name_ro: "Slobozia Șirăuți", name_ru: "Слобозия-Ширеуцы" },
  { name_ro: "Stăuceni", name_ru: "Ставчены" },
  { name_ro: "Bădragii Vechi", name_ru: "Старые Бадражи" },
  { name_ro: "Bilicenii Vechi", name_ru: "Старые Биличены" },
  { name_ro: "Caracușenii Vechi", name_ru: "Старые Каракушаны" },
  { name_ro: "Sîngerei", name_ru: "Сынжерей" },
  { name_ro: "Tabani", name_ru: "Табаны" },
  { name_ro: "Tețcani", name_ru: "Тецканы" },
  { name_ro: "Trebisăuți", name_ru: "Требисоуцы" },
  { name_ro: "Trinca", name_ru: "Тринка" },
  { name_ro: "Tîrnova", name_ru: "Тырново" },
  { name_ro: "Frunză", name_ru: "Фрунзэ" },
  { name_ro: "Hădărăuți", name_ru: "Ходороуцы" },
  { name_ro: "Ciocîlteni", name_ru: "Чокылтяны" },
  { name_ro: "Șirăuți", name_ru: "Ширеуцы" },
];
